# Generated by Django 3.1.3 on 2020-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='images/publication')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=25)),
                ('desc', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
