# Generated by Django 3.1.3 on 2020-11-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
