# Generated by Django 3.1.3 on 2020-11-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='BookType',
            new_name='Type',
        ),
    ]
