# Generated by Django 3.1.3 on 2020-11-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20201113_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='logo',
            new_name='img',
        ),
    ]
