# Generated by Django 3.1.3 on 2020-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
