# Generated by Django 3.1.3 on 2020-11-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20201128_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
