# Generated by Django 3.1.3 on 2020-11-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='images/author')),
                ('desc', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
