# Generated by Django 3.1.3 on 2020-12-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='expired_on',
            field=models.DateField(),
        ),
    ]
