# Generated by Django 3.1.3 on 2020-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetail', '0004_auto_20201117_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebookdetail',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issuebookdetail',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
