# Generated by Django 3.1.3 on 2020-11-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDetail', '0005_auto_20201117_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebookdetail',
            old_name='status',
            new_name='return_status',
        ),
    ]
