# Generated by Django 3.1.3 on 2020-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetail', '0009_issuebookdetail_fine_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebookdetail',
            name='sent_email',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
