# Generated by Django 3.1.3 on 2020-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDetail', '0010_issuebookdetail_sent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
    ]
