# Generated by Django 3.1.3 on 2020-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='storey',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
